language: node_js
node_js:
  - 5.6

notifications:
  email:
    recipients:
      - chiragghanshani@gmail.com
      - khoipham7501@gmail.com
      - achernan5@uh.edu
    on_success: always 
    on_failure: always

services:
  - mysql

before_script:
  - echo "USE mysql;\nUPDATE user SET password=PASSWORD('agile') WHERE user='root';\nFLUSH PRIVILEGES;\n" | mysql -u root
  - echo "mysql -uroot -pagile < db.sql && mysql -uroot -pagile < db_inserts.sql && mysql -uroot -pagile < db_triggers.sql" | bash
